FROM resin/rpi-raspbian:stretch

MAINTAINER Dirk Hessenmueller  <dirk.hessenmueller@anfang.hopto.org>


RUN apt-get update && \
    apt-get install -y php-mysql php-fpm \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/^listen = .*/listen = 9000/g' /etc/php/7.0/fpm/pool.d/www.conf

EXPOSE 9000

CMD php-fpm7.0 --force-stderr --nodaemonize --fpm-config /etc/php/7.0/fpm/php-fpm.conf

