version: '3.3'

services:
  web:
    image: dhessenm/armhf-nginx
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.htype==front
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt:ro"

