version: '3.3'

services:
  nx:
    image: dhessenm/armhf-nginx:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.htype==front
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
    networks:
      - wp

  wp:
    image: dhessenm/armhf-fpm:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.htype==front
    networks:
      - wp
      - db

  db:
    image: dhessenm/armhf-mysql:latest
    deploy:
      replicas: 1
    networks:
      - db

networks:
  wp:
  db:


