- hosts: manager
  become: Yes
  tasks:
    - name: Show facts
      # debug: var=hostvars[inventory_hostname] verbosity=4
      # debug: var=hostvars[inventory_hostname] 
      debug: var=ansible_eth0.ipv4.address

